// Code generated by Icestudio 0.10-rc1

`default_nettype none

//---- Top entity
module main #(
 parameter vd89b75 = 6
) (
 input v1e180c,
 input v644d5d,
 output vb21dfa,
 output v013ddf,
 output vd55cd2,
 output v32287a,
 output [0:2] vinit
);
 localparam p7 = vd89b75;
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 wire w24;
 wire w25;
 wire w26;
 wire w27;
 wire w28;
 wire w29;
 assign w8 = v1e180c;
 assign w18 = v644d5d;
 assign vb21dfa = w20;
 assign w20 = v644d5d;
 assign w21 = v644d5d;
 assign v013ddf = w21;
 assign vd55cd2 = w28;
 assign v32287a = w29;
 assign w10 = w9;
 assign w11 = w9;
 assign w11 = w10;
 assign w12 = w9;
 assign w12 = w10;
 assign w12 = w11;
 assign w13 = w9;
 assign w13 = w10;
 assign w13 = w11;
 assign w13 = w12;
 assign w14 = w9;
 assign w14 = w10;
 assign w14 = w11;
 assign w14 = w12;
 assign w14 = w13;
 assign w15 = w9;
 assign w15 = w10;
 assign w15 = w11;
 assign w15 = w12;
 assign w15 = w13;
 assign w15 = w14;
 assign w16 = w9;
 assign w16 = w10;
 assign w16 = w11;
 assign w16 = w12;
 assign w16 = w13;
 assign w16 = w14;
 assign w16 = w15;
 assign w20 = w18;
 assign w21 = w18;
 assign w21 = w20;
 assign w22 = w1;
 assign w23 = w2;
 assign w26 = w3;
 assign w28 = w19;
 assign w29 = w27;
 v8b89a5 v7aec62 (
  .vc24d9f(w0),
  .vb55943(w10),
  .vef4cea(w17)
 );
 v8b89a5 v8ba332 (
  .vef4cea(w0),
  .vc24d9f(w1),
  .vb55943(w11)
 );
 v8b89a5 vaff3bb (
  .vef4cea(w1),
  .vc24d9f(w2),
  .vb55943(w12)
 );
 v8b89a5 vcc4c2c (
  .vef4cea(w2),
  .vc24d9f(w3),
  .vb55943(w13)
 );
 v8b89a5 v168c2a (
  .vef4cea(w3),
  .vc24d9f(w4),
  .vb55943(w14)
 );
 v8b89a5 vdbb3f3 (
  .vef4cea(w4),
  .vc24d9f(w5),
  .vb55943(w15)
 );
 v8b89a5 v6b282d (
  .vef4cea(w5),
  .vc24d9f(w6),
  .vb55943(w16)
 );
 v8b89a5 v0bd418 (
  .vef4cea(w6),
  .vb55943(w9),
  .vc24d9f(w27)
 );
 v6a5074 #(
  .v100e1b(p7)
 ) vdb95cd (
  .v0daa9e(w8),
  .v2efea4(w9)
 );
 ve9ceb2 v2f2b22 (
  .vcbab45(w19),
  .v3ca442(w24),
  .v0e28cb(w25)
 );
 v528969 v676072 (
  .vcbab45(w17),
  .v0e28cb(w18),
  .v3ca442(w19)
 );
 ve9ceb2 v35e182 (
  .v0e28cb(w22),
  .v3ca442(w23),
  .vcbab45(w25)
 );
 ve9ceb2 va11654 (
  .vcbab45(w24),
  .v3ca442(w26),
  .v0e28cb(w27)
 );
 assign vinit = 3'b000;
endmodule

//---- Top entity
module v8b89a5 (
 input vb55943,
 input vef4cea,
 output vc24d9f
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = vef4cea;
 assign w1 = vb55943;
 assign vc24d9f = w2;
 v8b89a5_v526aa2 v526aa2 (
  .d(w0),
  .clk(w1),
  .q(w2)
 );
endmodule

//---------------------------------------------------
//-- Flip-flop D
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Delay flip-flop
//---------------------------------------------------

module v8b89a5_v526aa2 (
 input clk,
 input d,
 output q
);
 // D flip-flop
 
 reg q = 1'b0;
 
 always @(posedge clk)
 begin
   q <= d;
 end
 
 
endmodule
//---- Top entity
module v6a5074 #(
 parameter v100e1b = 22
) (
 input v0daa9e,
 output v2efea4
);
 localparam p2 = v100e1b;
 wire w0;
 wire w1;
 assign v2efea4 = w0;
 assign w1 = v0daa9e;
 v6a5074_vac7386 #(
  .N(p2)
 ) vac7386 (
  .clk_out(w0),
  .clk_in(w1)
 );
endmodule

//---------------------------------------------------
//-- PrescalerN
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Parametric N-bits prescaler
//---------------------------------------------------

module v6a5074_vac7386 #(
 parameter N = 0
) (
 input clk_in,
 output clk_out
);
 //-- Number of bits of the prescaler
 //parameter N = 22;
 
 //-- divisor register
 reg [N-1:0] divcounter;
 
 //-- N bit counter
 always @(posedge clk_in)
   divcounter <= divcounter + 1;
 
 //-- Use the most significant bit as output
 assign clk_out = divcounter[N-1];
endmodule
//---- Top entity
module ve9ceb2 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 ve9ceb2_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- XOR
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- XOR logic gate
//---------------------------------------------------

module ve9ceb2_vf4938a (
 input a,
 input b,
 output c
);
 // XOR logic gate
 
 assign c = a ^ b;
endmodule
//---- Top entity
module v528969 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v528969_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- OR
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- OR logic gate
//---------------------------------------------------

module v528969_vf4938a (
 input a,
 input b,
 output c
);
 // OR logic gate
 
 assign c = a | b;
endmodule
